.TH SPEED\-DIAL 1
speed\-dial\-VERSION
.SH NAME
speed\-dial \- create gnuplot charts from ledger data
.SH SYNOPSIS
.B ledgerplot
.RB [ \-v ]
.SH DEPENDS ON
racket
.SH DESCRIPTION
Speed-dial is a command-line application that can group commands and scripts
in an easy to use menu.
.SH CONFIGURATION
.TP
.B speed-dial.conf
As a user, do:
mkdir -p ~/.config/speed-dial
cp /usr/local/share/speed\-dial/speed-dial.conf ~/.config/speed-dial/speed-dial.conf
and add menu-items to the file as needed.
.B menu\-items
Beware that all commands are parsed and evaluated.
Put something dangerous in the speed\-dial.conf and
it will be executed!
.SH USAGE
Just run the application:
speed\-dial
.SH SEE ALSO
.BR speed\-dial (1)
.SH BUGS
None that I know of.
.SH EXAMPLES
See /usr/local/share/speed-dial/speed-dial.conf
